export const PHONE_COUNTRY_CODES = [
  { code: "+93", label: "Afghanistan (+93)" },
  { code: "+355", label: "Albania (+355)" },
  { code: "+213", label: "Algeria (+213)" },
  { code: "+376", label: "Andorra (+376)" },
  { code: "+244", label: "Angola (+244)" },
  { code: "+54", label: "Argentina (+54)" },
  { code: "+374", label: "Armenia (+374)" },
  { code: "+61", label: "Australia (+61)" },
  { code: "+43", label: "Austria (+43)" },
  { code: "+994", label: "Azerbaijan (+994)" },
  { code: "+973", label: "Bahrain (+973)" },
  { code: "+880", label: "Bangladesh (+880)" },
  { code: "+375", label: "Belarus (+375)" },
  { code: "+32", label: "Belgium (+32)" },
  { code: "+501", label: "Belize (+501)" },
  { code: "+229", label: "Benin (+229)" },
  { code: "+975", label: "Bhutan (+975)" },
  { code: "+591", label: "Bolivia (+591)" },
  { code: "+387", label: "Bosnia and Herzegovina (+387)" },
  { code: "+267", label: "Botswana (+267)" },
  { code: "+55", label: "Brazil (+55)" },
  { code: "+673", label: "Brunei (+673)" },
  { code: "+359", label: "Bulgaria (+359)" },
  { code: "+226", label: "Burkina Faso (+226)" },
  { code: "+257", label: "Burundi (+257)" },
  { code: "+855", label: "Cambodia (+855)" },
  { code: "+237", label: "Cameroon (+237)" },
  { code: "+1", label: "Canada (+1)" },
  { code: "+238", label: "Cape Verde (+238)" },
  { code: "+236", label: "Central African Republic (+236)" },
  { code: "+235", label: "Chad (+235)" },
  { code: "+56", label: "Chile (+56)" },
  { code: "+86", label: "China (+86)" },
  { code: "+57", label: "Colombia (+57)" },
  { code: "+269", label: "Comoros (+269)" },
  { code: "+242", label: "Congo (+242)" },
  { code: "+243", label: "Congo DR (+243)" },
  { code: "+506", label: "Costa Rica (+506)" },
  { code: "+385", label: "Croatia (+385)" },
  { code: "+53", label: "Cuba (+53)" },
  { code: "+357", label: "Cyprus (+357)" },
  { code: "+420", label: "Czech Republic (+420)" },
  { code: "+45", label: "Denmark (+45)" },
  { code: "+253", label: "Djibouti (+253)" },
  { code: "+593", label: "Ecuador (+593)" },
  { code: "+20", label: "Egypt (+20)" },
  { code: "+503", label: "El Salvador (+503)" },
  { code: "+240", label: "Equatorial Guinea (+240)" },
  { code: "+291", label: "Eritrea (+291)" },
  { code: "+372", label: "Estonia (+372)" },
  { code: "+251", label: "Ethiopia (+251)" },
  { code: "+679", label: "Fiji (+679)" },
  { code: "+358", label: "Finland (+358)" },
  { code: "+33", label: "France (+33)" },
  { code: "+241", label: "Gabon (+241)" },
  { code: "+220", label: "Gambia (+220)" },
  { code: "+995", label: "Georgia (+995)" },
  { code: "+49", label: "Germany (+49)" },
  { code: "+233", label: "Ghana (+233)" },
  { code: "+30", label: "Greece (+30)" },
  { code: "+502", label: "Guatemala (+502)" },
  { code: "+224", label: "Guinea (+224)" },
  { code: "+245", label: "Guinea-Bissau (+245)" },
  { code: "+592", label: "Guyana (+592)" },
  { code: "+509", label: "Haiti (+509)" },
  { code: "+504", label: "Honduras (+504)" },
  { code: "+36", label: "Hungary (+36)" },
  { code: "+354", label: "Iceland (+354)" },
  { code: "+91", label: "India (+91)" },
  { code: "+62", label: "Indonesia (+62)" },
  { code: "+98", label: "Iran (+98)" },
  { code: "+964", label: "Iraq (+964)" },
  { code: "+353", label: "Ireland (+353)" },
  { code: "+972", label: "Israel (+972)" },
  { code: "+39", label: "Italy (+39)" },
  { code: "+225", label: "Ivory Coast (+225)" },
  { code: "+81", label: "Japan (+81)" },
  { code: "+962", label: "Jordan (+962)" },
  { code: "+7", label: "Kazakhstan (+7)" },
  { code: "+254", label: "Kenya (+254)" },
  { code: "+965", label: "Kuwait (+965)" },
  { code: "+996", label: "Kyrgyzstan (+996)" },
  { code: "+856", label: "Laos (+856)" },
  { code: "+371", label: "Latvia (+371)" },
  { code: "+961", label: "Lebanon (+961)" },
  { code: "+266", label: "Lesotho (+266)" },
  { code: "+231", label: "Liberia (+231)" },
  { code: "+218", label: "Libya (+218)" },
  { code: "+423", label: "Liechtenstein (+423)" },
  { code: "+370", label: "Lithuania (+370)" },
  { code: "+352", label: "Luxembourg (+352)" },
  { code: "+261", label: "Madagascar (+261)" },
  { code: "+265", label: "Malawi (+265)" },
  { code: "+60", label: "Malaysia (+60)" },
  { code: "+960", label: "Maldives (+960)" },
  { code: "+223", label: "Mali (+223)" },
  { code: "+356", label: "Malta (+356)" },
  { code: "+222", label: "Mauritania (+222)" },
  { code: "+230", label: "Mauritius (+230)" },
  { code: "+52", label: "Mexico (+52)" },
  { code: "+373", label: "Moldova (+373)" },
  { code: "+377", label: "Monaco (+377)" },
  { code: "+976", label: "Mongolia (+976)" },
  { code: "+382", label: "Montenegro (+382)" },
  { code: "+212", label: "Morocco (+212)" },
  { code: "+258", label: "Mozambique (+258)" },
  { code: "+95", label: "Myanmar (+95)" },
  { code: "+264", label: "Namibia (+264)" },
  { code: "+977", label: "Nepal (+977)" },
  { code: "+31", label: "Netherlands (+31)" },
  { code: "+64", label: "New Zealand (+64)" },
  { code: "+505", label: "Nicaragua (+505)" },
  { code: "+227", label: "Niger (+227)" },
  { code: "+234", label: "Nigeria (+234)" },
  { code: "+389", label: "North Macedonia (+389)" },
  { code: "+47", label: "Norway (+47)" },
  { code: "+968", label: "Oman (+968)" },
  { code: "+92", label: "Pakistan (+92)" },
  { code: "+507", label: "Panama (+507)" },
  { code: "+595", label: "Paraguay (+595)" },
  { code: "+51", label: "Peru (+51)" },
  { code: "+63", label: "Philippines (+63)" },
  { code: "+48", label: "Poland (+48)" },
  { code: "+351", label: "Portugal (+351)" },
  { code: "+974", label: "Qatar (+974)" },
  { code: "+40", label: "Romania (+40)" },
  { code: "+7", label: "Russia (+7)" },
  { code: "+250", label: "Rwanda (+250)" },
  { code: "+966", label: "Saudi Arabia (+966)" },
  { code: "+221", label: "Senegal (+221)" },
  { code: "+381", label: "Serbia (+381)" },
  { code: "+232", label: "Sierra Leone (+232)" },
  { code: "+65", label: "Singapore (+65)" },
  { code: "+421", label: "Slovakia (+421)" },
  { code: "+386", label: "Slovenia (+386)" },
  { code: "+252", label: "Somalia (+252)" },
  { code: "+27", label: "South Africa (+27)" },
  { code: "+82", label: "South Korea (+82)" },
  { code: "+211", label: "South Sudan (+211)" },
  { code: "+34", label: "Spain (+34)" },
  { code: "+94", label: "Sri Lanka (+94)" },
  { code: "+249", label: "Sudan (+249)" },
  { code: "+597", label: "Suriname (+597)" },
  { code: "+46", label: "Sweden (+46)" },
  { code: "+41", label: "Switzerland (+41)" },
  { code: "+963", label: "Syria (+963)" },
  { code: "+886", label: "Taiwan (+886)" },
  { code: "+992", label: "Tajikistan (+992)" },
  { code: "+255", label: "Tanzania (+255)" },
  { code: "+66", label: "Thailand (+66)" },
  { code: "+228", label: "Togo (+228)" },
  { code: "+216", label: "Tunisia (+216)" },
  { code: "+90", label: "Turkey (+90)" },
  { code: "+993", label: "Turkmenistan (+993)" },
  { code: "+256", label: "Uganda (+256)" },
  { code: "+380", label: "Ukraine (+380)" },
  { code: "+971", label: "UAE (+971)" },
  { code: "+44", label: "United Kingdom (+44)" },
  { code: "+1", label: "United States (+1)" },
  { code: "+598", label: "Uruguay (+598)" },
  { code: "+998", label: "Uzbekistan (+998)" },
  { code: "+58", label: "Venezuela (+58)" },
  { code: "+84", label: "Vietnam (+84)" },
  { code: "+967", label: "Yemen (+967)" },
  { code: "+260", label: "Zambia (+260)" },
  { code: "+263", label: "Zimbabwe (+263)" },
] as const;

const PHONE_LOCAL_DIGIT_LENGTHS: Record<string, number> = {
  "+1": 10,
  "+7": 10,
  "+20": 10,
  "+27": 9,
  "+30": 10,
  "+31": 9,
  "+32": 9,
  "+33": 9,
  "+34": 9,
  "+39": 10,
  "+40": 9,
  "+41": 9,
  "+43": 10,
  "+44": 10,
  "+45": 8,
  "+46": 9,
  "+47": 8,
  "+48": 9,
  "+49": 10,
  "+51": 9,
  "+52": 10,
  "+54": 10,
  "+55": 11,
  "+56": 9,
  "+57": 10,
  "+58": 10,
  "+60": 9,
  "+61": 9,
  "+62": 10,
  "+63": 10,
  "+64": 9,
  "+65": 8,
  "+66": 9,
  "+81": 10,
  "+82": 10,
  "+84": 9,
  "+86": 11,
  "+90": 10,
  "+91": 10,
  "+92": 10,
  "+93": 9,
  "+94": 9,
  "+95": 9,
  "+98": 10,
  "+211": 9,
  "+212": 9,
  "+213": 9,
  "+216": 8,
  "+218": 9,
  "+220": 7,
  "+221": 9,
  "+223": 8,
  "+225": 10,
  "+230": 8,
  "+231": 8,
  "+232": 8,
  "+233": 9,
  "+234": 10,
  "+237": 9,
  "+242": 9,
  "+243": 9,
  "+249": 9,
  "+250": 9,
  "+251": 9,
  "+254": 9,
  "+255": 9,
  "+256": 9,
  "+260": 9,
  "+263": 9,
  "+351": 9,
  "+352": 9,
  "+353": 9,
  "+354": 7,
  "+355": 9,
  "+356": 8,
  "+357": 8,
  "+358": 9,
  "+359": 9,
  "+370": 8,
  "+371": 8,
  "+372": 8,
  "+373": 8,
  "+374": 8,
  "+375": 9,
  "+376": 6,
  "+380": 9,
  "+381": 9,
  "+385": 9,
  "+386": 8,
  "+387": 8,
  "+389": 8,
  "+420": 9,
  "+421": 9,
  "+423": 7,
  "+501": 7,
  "+502": 8,
  "+503": 8,
  "+504": 8,
  "+505": 8,
  "+506": 8,
  "+507": 8,
  "+591": 8,
  "+592": 7,
  "+593": 9,
  "+595": 9,
  "+597": 7,
  "+598": 8,
  "+966": 9,
  "+967": 9,
  "+968": 8,
  "+971": 9,
  "+972": 9,
  "+973": 8,
  "+974": 8,
  "+975": 8,
  "+976": 8,
  "+977": 10,
  "+992": 9,
  "+993": 8,
  "+994": 9,
  "+995": 9,
  "+996": 9,
  "+998": 9,
};

export function getPhoneLocalDigitsForCode(code: string): number {
  return PHONE_LOCAL_DIGIT_LENGTHS[code] ?? 10;
}

export const COUNTRY_CITY_OPTIONS = {
  Pakistan: [
    "Islamabad",
    "Rawalpindi",
    "Lahore",
    "Karachi",
    "Peshawar",
    "Quetta",
    "Multan",
    "Faisalabad",
    "Sialkot",
    "Gujranwala",
    "Hyderabad",
    "Abbottabad",
    "Bahawalpur",
    "Sukkur",
    "Mardan",
    "Sargodha",
    "Sahiwal",
    "Rahim Yar Khan",
    "Sheikhupura",
    "Mingora",
    "Dera Ghazi Khan",
    "Bahawalnagar",
    "Kasur",
    "Okara",
    "Muridke",
    "Nawabshah",
    "Chiniot",
    "Jhelum",
    "Gujrat",
    "Swabi",
    "Kohat",
    "Larkana",
    "Khuzdar",
    "Turbat",
    "Gwadar",
    "Sadiqabad",
    "Dera Ismail Khan",
    "Attock",
    "Muzaffargarh",
    "Vehari",
    "Jhang",
    "Kotri",
    "Pishin",
  ],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Al Ain", "Khor Fakkan", "Dibba Al Fujairah"],
  SaudiArabia: ["Riyadh", "Jeddah", "Makkah", "Madinah", "Dammam", "Khobar", "Taif", "Tabuk", "Jubail", "Abha", "Jazan", "Najran"],
  Qatar: ["Doha", "Al Wakrah", "Al Rayyan", "Al Khor", "Lusail", "Mesaieed", "Umm Salal", "Al Shamal"],
  "United Kingdom": ["London", "Birmingham", "Manchester", "Leeds", "Glasgow", "Liverpool", "Sheffield", "Bristol", "Edinburgh", "Cardiff", "Nottingham", "Leicester"],
  "United States": ["New York", "Washington", "Houston", "Los Angeles", "Chicago", "Dallas", "Miami", "Atlanta", "Phoenix", "Philadelphia", "San Antonio", "San Diego"],
  Canada: ["Toronto", "Mississauga", "Vancouver", "Calgary", "Ottawa", "Montreal", "Edmonton", "Winnipeg", "Quebec City", "Hamilton", "Surrey", "Halifax"],
  India: ["New Delhi", "Mumbai", "Bengaluru", "Chennai", "Kolkata", "Hyderabad", "Pune", "Ahmedabad", "Jaipur", "Surat", "Lucknow", "Kanpur"],
} as const;

export const COUNTRY_LIST = [
  "Pakistan",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo DR",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export const CITY_COUNTRY_OPTIONS = [
  "Kabul, Afghanistan",
  "Tirana, Albania",
  "Algiers, Algeria",
  "Andorra la Vella, Andorra",
  "Luanda, Angola",
  "Buenos Aires, Argentina",
  "Yerevan, Armenia",
  "Canberra, Australia",
  "Vienna, Austria",
  "Baku, Azerbaijan",
  "Manama, Bahrain",
  "Dhaka, Bangladesh",
  "Bridgetown, Barbados",
  "Minsk, Belarus",
  "Brussels, Belgium",
  "Belmopan, Belize",
  "Porto-Novo, Benin",
  "Thimphu, Bhutan",
  "Sucre, Bolivia",
  "Sarajevo, Bosnia and Herzegovina",
  "Gaborone, Botswana",
  "Brasilia, Brazil",
  "Bandar Seri Begawan, Brunei",
  "Sofia, Bulgaria",
  "Ouagadougou, Burkina Faso",
  "Gitega, Burundi",
  "Phnom Penh, Cambodia",
  "Yaounde, Cameroon",
  "Ottawa, Canada",
  "Praia, Cape Verde",
  "Bangui, Central African Republic",
  "N'Djamena, Chad",
  "Santiago, Chile",
  "Beijing, China",
  "Bogota, Colombia",
  "Moroni, Comoros",
  "Brazzaville, Congo",
  "Kinshasa, Congo DR",
  "San Jose, Costa Rica",
  "Zagreb, Croatia",
  "Havana, Cuba",
  "Nicosia, Cyprus",
  "Prague, Czech Republic",
  "Copenhagen, Denmark",
  "Djibouti, Djibouti",
  "Santo Domingo, Dominican Republic",
  "Quito, Ecuador",
  "Cairo, Egypt",
  "San Salvador, El Salvador",
  "Malabo, Equatorial Guinea",
  "Asmara, Eritrea",
  "Tallinn, Estonia",
  "Addis Ababa, Ethiopia",
  "Suva, Fiji",
  "Helsinki, Finland",
  "Paris, France",
  "Libreville, Gabon",
  "Banjul, Gambia",
  "Tbilisi, Georgia",
  "Berlin, Germany",
  "Accra, Ghana",
  "Athens, Greece",
  "Guatemala City, Guatemala",
  "Conakry, Guinea",
  "Bissau, Guinea-Bissau",
  "Georgetown, Guyana",
  "Port-au-Prince, Haiti",
  "Tegucigalpa, Honduras",
  "Budapest, Hungary",
  "Reykjavik, Iceland",
  "New Delhi, India",
  "Jakarta, Indonesia",
  "Tehran, Iran",
  "Baghdad, Iraq",
  "Dublin, Ireland",
  "Jerusalem, Israel",
  "Rome, Italy",
  "Yamoussoukro, Ivory Coast",
  "Tokyo, Japan",
  "Amman, Jordan",
  "Astana, Kazakhstan",
  "Nairobi, Kenya",
  "Kuwait City, Kuwait",
  "Bishkek, Kyrgyzstan",
  "Vientiane, Laos",
  "Riga, Latvia",
  "Beirut, Lebanon",
  "Maseru, Lesotho",
  "Monrovia, Liberia",
  "Tripoli, Libya",
  "Vaduz, Liechtenstein",
  "Vilnius, Lithuania",
  "Luxembourg City, Luxembourg",
  "Antananarivo, Madagascar",
  "Lilongwe, Malawi",
  "Kuala Lumpur, Malaysia",
  "Male, Maldives",
  "Bamako, Mali",
  "Valletta, Malta",
  "Nouakchott, Mauritania",
  "Port Louis, Mauritius",
  "Mexico City, Mexico",
  "Chisinau, Moldova",
  "Monaco, Monaco",
  "Ulaanbaatar, Mongolia",
  "Podgorica, Montenegro",
  "Rabat, Morocco",
  "Maputo, Mozambique",
  "Naypyidaw, Myanmar",
  "Windhoek, Namibia",
  "Kathmandu, Nepal",
  "Amsterdam, Netherlands",
  "Wellington, New Zealand",
  "Managua, Nicaragua",
  "Niamey, Niger",
  "Abuja, Nigeria",
  "Pyongyang, North Korea",
  "Skopje, North Macedonia",
  "Oslo, Norway",
  "Muscat, Oman",
  "Islamabad, Pakistan",
  "Rawalpindi, Pakistan",
  "Lahore, Pakistan",
  "Karachi, Pakistan",
  "Peshawar, Pakistan",
  "Quetta, Pakistan",
  "Multan, Pakistan",
  "Faisalabad, Pakistan",
  "Panama City, Panama",
  "Asuncion, Paraguay",
  "Lima, Peru",
  "Manila, Philippines",
  "Warsaw, Poland",
  "Lisbon, Portugal",
  "Doha, Qatar",
  "Bucharest, Romania",
  "Moscow, Russia",
  "Kigali, Rwanda",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Makkah, Saudi Arabia",
  "Madinah, Saudi Arabia",
  "Dakar, Senegal",
  "Belgrade, Serbia",
  "Freetown, Sierra Leone",
  "Singapore, Singapore",
  "Bratislava, Slovakia",
  "Ljubljana, Slovenia",
  "Mogadishu, Somalia",
  "Pretoria, South Africa",
  "Seoul, South Korea",
  "Juba, South Sudan",
  "Madrid, Spain",
  "Colombo, Sri Lanka",
  "Khartoum, Sudan",
  "Paramaribo, Suriname",
  "Stockholm, Sweden",
  "Bern, Switzerland",
  "Damascus, Syria",
  "Taipei, Taiwan",
  "Dushanbe, Tajikistan",
  "Dodoma, Tanzania",
  "Bangkok, Thailand",
  "Lome, Togo",
  "Tunis, Tunisia",
  "Ankara, Turkey",
  "Ashgabat, Turkmenistan",
  "Kampala, Uganda",
  "Kyiv, Ukraine",
  "Abu Dhabi, UAE",
  "Dubai, UAE",
  "Sharjah, UAE",
  "London, United Kingdom",
  "New York, United States",
  "Washington, United States",
  "Montevideo, Uruguay",
  "Tashkent, Uzbekistan",
  "Caracas, Venezuela",
  "Hanoi, Vietnam",
  "Sanaa, Yemen",
  "Lusaka, Zambia",
  "Harare, Zimbabwe",
] as const;
